import ProjectNav from "@/components/body/ProjectNav";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <div>
      <ProjectNav />
      {children}
    </div>
  );
};

export default layout;
